name: Release Build

# Build, create a release, and attach build artifacts to the release
# when a version tag is pushed.
#
# The tag needs to be pushed by name, as `git push --tags` to push all
# tags does not appear to trigger the action.
#
# The versioned release process is similar to the following:
# 1. Add an annotated tag with the release version string.
#        git tag -a v0.9.2
# 2. Draft a message for the annotated tag similar to the following.
#        Release v0.9.2
#
#        Release Highlights
#        - Brief description of new item 1.
#        - Brief description of new item 2.
# 3. Push the tag to GitHub.
#        git push origin v0.9.2

on:
  push:
    tags:       
      - v*

jobs:
  linux:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
        - {
            name: "Ubuntu GCC Release",
            artifact: "gfxreconstruct-dev-ubuntu-gcc-release",
            os: ubuntu-latest,
            cc: "gcc", cxx: "g++"
          }
    steps:
    - name: Clone Repository
      uses: actions/checkout@v1
    - name: Install Dependencies
      run: |
        sudo apt-get install -y libx11-xcb-dev libxcb-keysyms1-dev libwayland-dev libxrandr-dev liblz4-dev libzstd-dev
    - name: Run Build Script
      run: |
        python3 scripts/build.py --skip-check-code-style --skip-tests
    - name: Prepare Artifact
      run: |
        cp LICENSE.txt build/linux/x64/bin/
        cp USAGE_desktop.md build/linux/x64/bin/
        rm -rf build/linux/x64/bin/staging-json
        mv build/linux/x64/bin gfxreconstruct-dev
    - name: Upload Artifact
      uses: actions/upload-artifact@v1
      with:
        name: ${{ matrix.config.artifact }}
        path: ./gfxreconstruct-dev
  
  windows:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
        - {
            name: "Windows MSVC Release",
            artifact: "gfxreconstruct-dev-windows-msvc-release",
            os: windows-latest,
            cc: "cl", cxx: "cl"
          }
    steps:
    - name: Clone Repository
      uses: actions/checkout@v1
    - name: Run Build Script
      run: |
        python scripts/build.py --skip-check-code-style --skip-tests
    - name: Prepare Artifact
      run: |
        copy LICENSE.txt build/windows/x64/bin/
        copy USAGE_desktop.md build/windows/x64/bin/
        move build/windows/x64/bin gfxreconstruct-dev
    - name: Upload Artifact
      uses: actions/upload-artifact@v1
      with:
        name: ${{ matrix.config.artifact }}
        path: ./gfxreconstruct-dev

  android:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
        - {
            name: "Android Release/Debug",
            artifact: "gfxreconstruct-dev-android",
            os: ubuntu-latest
          }
    steps:
    - name: Clone Repository
      uses: actions/checkout@v1
    - name: Update Submodules
      run: |
        git submodule update --init
    - name: Gradle Build
      run: |
        cd android
        sh gradlew assembleRelease assembleDebug
    - name: Prepare Artifact
      run: |
        mkdir gfxreconstruct-dev
        mkdir gfxreconstruct-dev/layer
        mkdir gfxreconstruct-dev/tools
        cp LICENSE.txt gfxreconstruct-dev/
        cp USAGE_android.md gfxreconstruct-dev/
        cp -r android/layer/build/intermediates/cmake/release/obj/arm64-v8a gfxreconstruct-dev/layer/
        cp -r android/layer/build/intermediates/cmake/release/obj/armeabi-v7a gfxreconstruct-dev/layer/
        cp android/tools/replay/build/outputs/apk/debug/replay-debug.apk gfxreconstruct-dev/tools/
        cp android/scripts/gfxrecon.py gfxreconstruct-dev/tools/
    - name: Upload Artifact
      uses: actions/upload-artifact@v1
      with:
        name: ${{ matrix.config.artifact }}
        path: ./gfxreconstruct-dev

  release:
    name: Create Release for Tag
    runs-on: ubuntu-latest
    needs: [ linux, windows, android ]
    steps:
    - name: Clone Repository
      uses: actions/checkout@v1
    - name: Get Tag Body
      id: get_tag_body
      run: |
        tag_name=`echo "${{ github.ref }}" | cut -d "/" -f 3`
        tag_body=`git tag -l --format='%(body)' $tag_name`
        echo "::set-output name=tag_body::$tag_body"
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: "${{ steps.get_tag_body.outputs.tag_body }}"
        draft: false
        prerelease: false
    - name: Upload Release URL
      run: |
        echo "${{ steps.create_release.outputs.upload_url }}" > ./release_url
    - uses: actions/upload-artifact@v1
      with:
        name: release_url
        path: ./release_url

  publish:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    needs: release
    strategy:
      fail-fast: false
      matrix:
        config:
        - {
            name: "Upload Ubuntu Release Artifact",
            os: ubuntu-latest,
            artifact: "gfxreconstruct-dev-ubuntu-gcc-release",
            command: "tar czf",
            suffix: "ubuntu-gcc.tar.gz",
            type: "application/x-gtar"
          }
        - {
            name: "Upload Windows Release Artifact",
            os: ubuntu-latest,
            artifact: "gfxreconstruct-dev-windows-msvc-release",
            command: "zip -r",
            suffix: "windows-msvc.zip",
            type: "application/zip"
          }
        - {
            name: "Upload Android Release Artifact",
            os: ubuntu-latest,
            artifact: "gfxreconstruct-dev-android",
            command: "zip -r",
            suffix: "android.zip",
            type: "application/zip"
          }
    steps:
    - name: Get Tag Name
      id: get_tag_name
      run: |
        tag_name=`echo "${{ github.ref }}" | cut -d "/" -f 3`
        echo "::set-output name=tag_name::$tag_name"
    - name: Download Artifact
      uses: actions/download-artifact@v1
      with:
        name: ${{ matrix.config.artifact }}
        path: ./gfxreconstruct-${{ steps.get_tag_name.outputs.tag_name }}
    - name: Make Release Artifact
      run: |
        ${{ matrix.config.command }} gfxreconstruct-${{ steps.get_tag_name.outputs.tag_name }}-${{ matrix.config.suffix }} gfxreconstruct-${{ steps.get_tag_name.outputs.tag_name }}
    - name: Download Release URL
      uses: actions/download-artifact@v1
      with:
        name: release_url
        path: ./
    - name: Set Upload URL
      id: set_upload_url
      run: |
        upload_url=`cat ./release_url`
        echo "::set-output name=upload_url::$upload_url"
    - name: Upload Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.set_upload_url.outputs.upload_url }}
        asset_name: gfxreconstruct-${{ steps.get_tag_name.outputs.tag_name }}-${{ matrix.config.suffix }}
        asset_path: ./gfxreconstruct-${{ steps.get_tag_name.outputs.tag_name }}-${{ matrix.config.suffix }}
        asset_content_type: ${{ matrix.config.type }}
  